### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by tjorim**

### CODE REVIEW

**Comment by meichthys** [comment]
Nice! As always, is much appreciated when an issue is addressed with an associated pull request!

**Comment by tjorim** [comment]
@meichthys one More thing the hacs check fails on which I can't resolve myself:
`2022-10-11T01:38:18.4358916Z ##[error] <Validation topics> failed:  The repository has no valid topics (More info: https://hacs.xyz/docs/publish/include#check-repository )`.
Some topics need to be added to this repo.

Then, because of
> Only the owner of the repository or a major contributor to it can submit a PR to have it included as a default.
I can't open the PR myself, it looks easy enough to do here: https://github.com/hacs/default

**Comment by meichthys** [comment]
Ok thanks. I'll take care of this later today 👍

**Comment by tjorim** [comment]
@meichthys Care to add the 'HACKTOBERFEST-ACCEPTED' label to this PR?

**Comment by meichthys** [comment]
@tjorim  i'm not even sure how to do that.

**Comment by meichthys** [comment]
Is that enough?

**Comment by tjorim** [comment]
Perfect, thanks!

**Pull request merged**
